/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "primary-fixed": "var(--color-primary-fixed)",
        "on-error-container": "var(--color-on-error-container)",
        "surface-container-low": "var(--color-surface-container-low)",
        "outline-variant": "var(--color-outline-variant)",
        "primary-container": "var(--color-primary-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "on-error": "var(--color-on-error)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-secondary": "var(--color-on-secondary)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "error": "var(--color-error)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-primary": "var(--color-on-primary)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-bright": "var(--color-surface-bright)",
        "outline": "var(--color-outline)",
        "on-primary-container": "var(--color-on-primary-container)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "surface-container": "var(--color-surface-container)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "background": "var(--color-background)",
        "on-tertiary": "var(--color-on-tertiary)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "tertiary": "var(--color-tertiary)",
        "primary": "var(--color-primary)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "on-background": "var(--color-on-background)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "secondary": "var(--color-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "surface": "var(--color-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "error-container": "var(--color-error-container)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1024px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1024px",
      },
      keyframes: {
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
          "100%": { transform: "translateY(0px)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "fade-in": "fadeIn 1s ease-out forwards",
      },
    },
  },
  plugins: [],
};
