/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#debfc2",
        "surface-container-highest": "#e4e2e2",
        "tertiary-container": "#e3e2da",
        "secondary-fixed-dim": "#a7d1a5",
        "primary-fixed": "#fbdbde",
        "on-error-container": "#93000a",
        "surface-container-low": "#f5f3f3",
        "outline-variant": "#d2c3c4",
        "primary-container": "#fadadd",
        "surface-container-high": "#eae8e7",
        "inverse-on-surface": "#f2f0f0",
        "on-tertiary-container": "#64645e",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#debfc2",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e4e3db",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#c8c7bf",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#281719",
        "inverse-surface": "#303030",
        "surface-bright": "#fbf9f8",
        "outline": "#807475",
        "on-primary-container": "#765e61",
        "on-primary-fixed-variant": "#574144",
        "surface-container": "#efeded",
        "on-tertiary-fixed": "#1b1c17",
        "background": "#fbf9f8",
        "on-tertiary": "#ffffff",
        "on-secondary-container": "#476d49",
        "on-tertiary-fixed-variant": "#474742",
        "tertiary": "#5f5f59",
        "primary": "#70585b",
        "surface-dim": "#dbd9d9",
        "surface-variant": "#e4e2e2",
        "on-surface": "#1b1c1c",
        "on-secondary-fixed-variant": "#294f2d",
        "on-background": "#1b1c1c",
        "on-surface-variant": "#4f4445",
        "secondary": "#416743",
        "secondary-container": "#c2eec0",
        "secondary-fixed": "#c2eec0",
        "on-secondary-fixed": "#002107",
        "surface": "#fbf9f8",
        "surface-tint": "#70585b",
        "error-container": "#ffdad6",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-mobile": "20px",
        gutter: "24px",
        "container-max": "1024px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "headline-md": ["Playfair Display"],
        "body-lg": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Playfair Display"],
        "display-lg": ["Playfair Display"],
        "label-sm": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "1.0", letterSpacing: "0.08em", fontWeight: "600" }],
      },
      maxWidth: {
        "container-max": "1024px",
      },
      keyframes: {
        float: {
          "0%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-10px)" },
          "100%": { transform: "translateY(0px)" },
        },
        fadeIn: {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "fade-in": "fadeIn 1s ease-out forwards",
      },
    },
  },
  plugins: [],
};
